#include "common.h"

enum SYMBOLS
{
	QUESTION_MARK = 300,
	STAR,
	PLUS,
	OPEN_PAREN,
	CLOSE_PAREN,
	OPEN_BRACKET, // 305
	CLOSE_BRACKET,
	OR,
	CONCATENATION,
	STACK_BOTTOM,
	END, // 310
	DOT,
	START
};

enum OPERATIONS
{
	OP_NONE,
	OP_SHIFT,
	OP_REDUCE,
	OP_EQUAL,
	OP_FIN
};

#define EPSILON 400
#define NO_END 0

short precedence_table[11][10] =
{
	// ?		*			+			(			)			[			]			|			.			STACK_BOTTOM
	{OP_NONE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_REDUCE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_SHIFT,	OP_SHIFT}, // ?
	{OP_NONE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_REDUCE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_SHIFT,	OP_SHIFT}, // *
	{OP_NONE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_REDUCE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_SHIFT,	OP_SHIFT}, // +
	{OP_REDUCE,	OP_REDUCE,	OP_REDUCE,	OP_SHIFT,	OP_NONE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_SHIFT,	OP_SHIFT}, // (
	{OP_REDUCE,	OP_REDUCE,	OP_REDUCE,	OP_EQUAL,	OP_REDUCE,	OP_NONE,	OP_NONE,	OP_REDUCE,	OP_REDUCE,	OP_NONE}, // )
	{OP_REDUCE,	OP_REDUCE,	OP_REDUCE,	OP_SHIFT,	OP_NONE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_SHIFT,	OP_SHIFT}, // [
	{OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE}, // ]
	{OP_REDUCE,	OP_REDUCE,	OP_REDUCE,	OP_SHIFT,	OP_REDUCE,	OP_NONE,	OP_NONE,	OP_REDUCE,	OP_REDUCE, OP_SHIFT}, // |
	{OP_REDUCE,	OP_REDUCE,	OP_REDUCE,	OP_SHIFT,	OP_REDUCE,	OP_NONE,	OP_NONE,	OP_SHIFT,	OP_REDUCE, OP_SHIFT}, // .
	{OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE,	OP_NONE}, // EMPTY LINE
	{OP_REDUCE,	OP_REDUCE,	OP_REDUCE,	OP_NONE,	OP_REDUCE,	OP_NONE,	OP_NONE,	OP_REDUCE,	OP_REDUCE,	OP_FIN} // END
};
